"""Install the ANIMATED Gen 5 (Black/White) battle sprites as strips.

Source: PokeAPI/sprites, sprites/pokemon/versions/generation-v/black-white/
animated/{id}.gif and animated/back/{id}.gif, downloaded to
tools/_vfx_dl/pokeapi_bw_anim/{front,back}/{id}.gif. Each GIF is unrolled
frame by frame -- disposal handled by hand, so a frame that only redraws
the part that moved is composited over the one before it -- every frame
cropped to the UNION of the opaque boxes (so the strip's frames share one
size and one anchor), identical consecutive frames merged (their delays
summed), and the result written as a GRID png:

    assets/mons/anim/{front,back}/<name>.png

with the metadata for all of them in data/mons_anim.lua:

    return { ["front:pikachu"] = { file = "...", w = 50, h = 46,
                                   cols = 12, n = 34,
                                   d = { 80, 80, 40, ... } },  -- ms
             ... }

<name> is the species id as lib/MonPack.lua keys it (lower case, letters
and digits only). Pixels are copied as they are.

    python tools/install_mon_anim.py [id ...]
"""
import json
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "_vfx_dl" / "pokeapi_bw_anim"
LIST = ROOT / "tools" / "_vfx_dl" / "pokeapi151.json"
OUT = ROOT / "assets" / "mons" / "anim"
META = ROOT / "data" / "mons_anim.lua"
MAX_W = 4096


def norm(name):
    return re.sub(r"[^a-z0-9]", "", name.lower())


def unroll(path):
    """All frames of a GIF as RGBA arrays of the full canvas, plus delays."""
    im = Image.open(path)
    w, h = im.size
    frames, delays = [], []
    canvas = np.zeros((h, w, 4), dtype=np.uint8)
    prev = canvas.copy()
    i = 0
    while True:
        try:
            im.seek(i)
        except EOFError:
            break
        disposal = getattr(im, "disposal_method", 0)
        delay = int(im.info.get("duration", 100) or 100)
        frame = np.array(im.convert("RGBA"))
        # composite the new frame over the working canvas
        before = canvas.copy()
        a = frame[..., 3:4].astype(np.float32) / 255.0
        canvas = (frame.astype(np.float32) * a
                  + canvas.astype(np.float32) * (1 - a)).astype(np.uint8)
        canvas[..., 3] = np.maximum(canvas[..., 3], frame[..., 3])
        frames.append(canvas.copy())
        delays.append(max(20, delay))
        if disposal == 2:
            canvas = np.zeros_like(canvas)
        elif disposal == 3:
            canvas = before
        i += 1
    return frames, delays


def install(idx, name):
    key = norm(name)
    entries = {}
    for side in ("front", "back"):
        src = SRC / side / f"{idx}.gif"
        if not src.exists():
            print(f"missing {src}")
            continue
        frames, delays = unroll(src)
        if not frames:
            continue
        # merge identical consecutive frames
        merged, md = [frames[0]], [delays[0]]
        for f, d in zip(frames[1:], delays[1:]):
            if np.array_equal(f, merged[-1]):
                md[-1] += d
            else:
                merged.append(f)
                md.append(d)
        frames, delays = merged, md
        # the union box
        alpha = np.stack([f[..., 3] for f in frames]).max(axis=0)
        ys, xs = np.where(alpha > 0)
        if len(ys) == 0:
            continue
        y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1
        fw, fh = int(x1 - x0), int(y1 - y0)
        n = len(frames)
        cols = max(1, min(n, MAX_W // fw))
        rows = (n + cols - 1) // cols
        grid = np.zeros((rows * fh, cols * fw, 4), dtype=np.uint8)
        for k, f in enumerate(frames):
            r, c = divmod(k, cols)
            grid[r * fh:(r + 1) * fh, c * fw:(c + 1) * fw] = f[y0:y1, x0:x1]
        out = OUT / side / f"{key}.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        Image.fromarray(grid, "RGBA").save(out, optimize=True)
        entries[f"{side}:{key}"] = {
            "file": f"{side}/{key}.png", "w": fw, "h": fh,
            "cols": cols, "n": n, "d": delays,
        }
    return entries


def write_meta(all_entries):
    lines = ["-- GENERATED by tools/install_mon_anim.py: the animated mon",
             "-- pack's strips. w,h = frame size; cols = frames per row;",
             "-- n = frames; d = each frame's hold in ms.", "return {"]
    for key in sorted(all_entries):
        e = all_entries[key]
        d = ", ".join(str(x) for x in e["d"])
        lines.append(f'  ["{key}"] = {{ file = "{e["file"]}", w = {e["w"]}, '
                     f'h = {e["h"]}, cols = {e["cols"]}, n = {e["n"]}, '
                     f'd = {{ {d} }} }},')
    lines.append("}")
    META.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    names = json.loads(LIST.read_text(encoding="utf-8"))["results"]
    only = set(int(a) for a in sys.argv[1:]) if len(sys.argv) > 1 else None
    all_entries = {}
    if META.exists() and only:
        # keep the entries of species not being redone
        try:
            txt = META.read_text(encoding="utf-8")
            for m in re.finditer(r'\["([a-z]+:[a-z0-9]+)"\] = \{ file = "([^"]+)", w = (\d+), h = (\d+), cols = (\d+), n = (\d+), d = \{ ([^}]*) \}', txt):
                all_entries[m.group(1)] = {
                    "file": m.group(2), "w": int(m.group(3)), "h": int(m.group(4)),
                    "cols": int(m.group(5)), "n": int(m.group(6)),
                    "d": [int(x) for x in m.group(7).split(",") if x.strip()],
                }
        except Exception:
            all_entries = {}
    total = 0
    for i, entry in enumerate(names, start=1):
        if only and i not in only:
            continue
        e = install(i, entry["name"])
        all_entries.update(e)
        total += len(e)
        for k, v in e.items():
            print(f"{k:24s} {v['w']}x{v['h']} x{v['n']} ({v['cols']} cols)")
    write_meta(all_entries)
    print(f"installed {total} strips; meta {META}")


if __name__ == "__main__":
    main()
